F-Secure/change-analyzer

change_analyzer/sequences_diff.py

Fix case when actual/expected xml are nan, which raise a TypeError exception

fix: fix the case when xmls were nan

---

Makefile

Enable Github releasing, add debug verbosity.
Change Makefile line endings to LF.

feat: enable github releasing

---

Makefile
setup.cfg

Add setup.cfg configure file for semantic-release.

fix: add config for semantic-release

---

change_analyzer/sequences_diff.py

any should be negated, otherwise we validate unintended diff

fix: fix diff validation

---

change_analyzer/wrappers/sequence_recorder.py

Enrich the page source with additional data from driver

feat: enrich page source with data from driver

---

.github/workflows/publish.yml
entrypoint.sh

Docker parameters changed to generate data.
Result parsing bug fixed.

test: docker generate results

---

.github/workflows/publish.yml

Change generate mode to replay and compare.

test: docker image use replay and compare

---

README.md

Add About section to Readme file

docs: add about section

---

setup.cfg

feat: enable pypi publish

---

.github/workflows/publish.yml

Add missing PYPI_TOKEN to github action.

fix: fix pypi publish

---

setup.py

Add missing dependency appium-python-client and remove the duplicated pandas

fix: add missing dependency

---

setup.py

Appium-python-client package is specified.

fix: fix requirements

---

change_analyzer/main.py

Add an argument for the total steps

feat: add steps as argument

---

setup.py

Update project homepage from Bitbucket to Github

doc: update project homepage

---

README.md

doc: add example of web.ini file

---

change_analyzer/main.py

Add possibility to define timeout for SUT in ini file.

feat: add timeout for start of SUT

---

change_analyzer/sequences_diff.py

Fix problem where compare file extension was wrong

fix: compare result compress fix

---

.github/workflows/publish.yml
setup.py

Change github action pytest python version to 3.7.10

chore: define precise python version

---

setup.py

Update dependencies to include what is needed for Reinforcement Learning feature

refactor: update dependencies

---

.github/workflows/publish.yml

Publish Docker images into public AWS ECR.

feat: publish docker images

---

.github/workflows/publish.yml

Remove previously broken Docker build and test.
Skip session tagging for AWS configure.

chore: adjust github action

---

.github/workflows/publish.yml

Add url of repo to Docker image tag.

chore: change docker image tagging

---

setup.py

fix: add more dependencies for explorer agent

---

setup.py

Migrate from tensorflow to pytorch to address security vulnerabilities

fix: migrate from tensorflow to pytorch

---

change_analyzer/agents/explorer_agent.py
change_analyzer/envs/app_env.py
change_analyzer/main.py
change_analyzer/spaces/discrete_app_action_space.py
change_analyzer/wrappers/sequence_recorder.py
config_ludwig_model.json
setup.py

Add initial building blocks for reinformcement learning workflow

feat: add initial building blocks for reinforcement learning

---

change_analyzer/agents/explorer_agent.py

Update explorer agent to use numpy array for images

update: Update explorer agent to use numpy array for images

---

change_analyzer/agents/explorer_agent.py

Fix explorer agent code by removing debugging info from initial developing phase

fix: fix explorer agent

---

change_analyzer/agents/explorer_agent.py
change_analyzer/main.py
pretrained_model/model_hyperparameters.json
pretrained_model/training_set_metadata.json

Add pretrained models option when using reinforcement learning

feat: add pretrained models option when using reinforcement learning
